# Generated by Django 4.1.4 on 2023-02-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico_y_enfermera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='id_comuna',
        ),
    ]
