# Generated by Django 4.1.4 on 2023-02-02 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App_tipo_terapia',
            fields=[
                ('id_app_tipo_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id_diabetes', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_diabetes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hipertension',
            fields=[
                ('id_hipertension', models.AutoField(primary_key=True, serialize=False)),
                ('estado_hipertension', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_paciente', models.CharField(max_length=100)),
                ('telegram_paciente', models.CharField(max_length=100)),
                ('diabetes_id', models.CharField(max_length=100)),
                ('hipertension', models.CharField(max_length=100)),
                ('paciente_familiar', models.CharField(max_length=100)),
                ('whatsapp_paciente', models.CharField(max_length=100)),
                ('celular_paciente', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_parentesco',
            fields=[
                ('id_tipo_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('horarios', models.CharField(max_length=100)),
                ('fonoaudiologo_id', models.CharField(max_length=100)),
                ('paciente_id', models.CharField(max_length=100)),
                ('id_app_tipo_terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.app_tipo_terapia')),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio_terapia',
            fields=[
                ('id_recordatorio_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('hora_recordatorio', models.CharField(max_length=100)),
                ('receta_id', models.CharField(max_length=100)),
                ('id_terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.terapia')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_documento',
            fields=[
                ('id_paciente_documento', models.AutoField(primary_key=True, serialize=False)),
                ('autorizado', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('documento_id', models.CharField(max_length=100)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Intensidad',
            fields=[
                ('id_intensidad', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_archivo_intensidad', models.CharField(max_length=100)),
                ('intensidad', models.CharField(max_length=100)),
                ('mindb', models.CharField(max_length=100)),
                ('maxdb', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=100)),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar_paciente',
            fields=[
                ('id_familiar_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('familiar', models.ManyToManyField(related_name='Familiar', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ManyToManyField(related_name='Paciente', to=settings.AUTH_USER_MODEL)),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.tipo_parentesco')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('rut_familiar', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
