# Generated by Django 4.1.4 on 2023-02-02 15:56

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_telegram', models.CharField(default='@', max_length=100, null=True)),
                ('telefono', models.CharField(default='+569', max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='App_documento',
            fields=[
                ('id_app_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('qr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id_audio', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_archivo_audio', models.CharField(max_length=100)),
                ('jitter_ppq5', models.CharField(max_length=100)),
                ('jitter_rap', models.CharField(max_length=100)),
                ('maximum_pitch', models.CharField(max_length=100)),
                ('error_jitter_ppq5', models.CharField(max_length=100)),
                ('error_jitter_rap', models.CharField(max_length=100)),
                ('error_maximum_pitch', models.CharField(max_length=100)),
                ('jitter_ppq5_IA', models.CharField(max_length=100)),
                ('jitter_rap_IA', models.CharField(max_length=100)),
                ('maximum_pitch_IA', models.CharField(max_length=100)),
                ('error_jitter_ppq5_IA', models.CharField(max_length=100)),
                ('error_jitter_rap_IA', models.CharField(max_length=100)),
                ('error_maximum_pitch_IA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='user-')),
                ('count_img', models.IntegerField(default=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_juego',
            fields=[
                ('id_tipo_juego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_juego', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vocalizacion',
            fields=[
                ('id_vocalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_archivo_vocalizacion', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('bpminute', models.CharField(max_length=100)),
                ('bpmeasure', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=100)),
            ],
        ),
    ]
