# Generated by Django 4.1.4 on 2023-02-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_juego',
        ),
    ]
