# Generated by Django 4.1.4 on 2023-02-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_tipo_juego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Tipo_usuario',
        ),
    ]
