# Generated by Django 4.1.4 on 2023-02-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0002_tipo_usuario'),
        ('app', '0005_delete_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Tipo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipologias.tipo_usuario'),
        ),
    ]
