# Generated by Django 4.1.4 on 2023-02-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_usuario_id_comuna'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comuna',
        ),
    ]
