# Generated by Django 4.1.4 on 2023-02-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_comuna'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
