# Generated by Django 4.1.4 on 2023-02-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_provincia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
