# Generated by Django 4.1.4 on 2023-02-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_comuna'),
        ('tipologias', '0002_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=100)),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia')),
            ],
        ),
    ]
