# Generated by Django 4.1.4 on 2023-02-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0003_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='id_provincia',
        ),
    ]
