# Generated by Django 4.1.4 on 2023-02-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_provincia'),
        ('tipologias', '0004_remove_comuna_id_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
        ),
    ]
