# Generated by Django 4.1.4 on 2023-02-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0006_comuna_id_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='id_region',
        ),
    ]
