# Generated by Django 4.1.4 on 2023-02-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0008_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='id_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipologias.region'),
            preserve_default=False,
        ),
    ]
