# Generated by Django 4.1.4 on 2023-02-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipologias', '0001_initial'),
        ('juegos', '0002_remove_juego_id_tipo_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='id_tipo_juego',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipologias.tipo_juego'),
            preserve_default=False,
        ),
    ]
